# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_solved_and_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedissue',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='solvedissue',
            name='github_pr_url',
            field=models.URLField(blank=True),
        ),
    ]
